"""
Telegram Bot - Gửi tín hiệu qua Telegram
"""

import requests
from typing import Dict
from config import settings


class TelegramBot:
    def __init__(self):
        self.token = settings.TELEGRAM_BOT_TOKEN
        self.chat_id = settings.TELEGRAM_CHAT_ID
        self.base_url = f"https://api.telegram.org/bot{self.token}"

    def send_message(self, text: str) -> bool:
        """Gửi message qua Telegram"""
        if not self.token or not self.chat_id:
            print("Telegram not configured. Skipping notification.")
            return False

        try:
            url = f"{self.base_url}/sendMessage"
            payload = {
                "chat_id": self.chat_id,
                "text": text,
                "parse_mode": "Markdown",
                "disable_web_page_preview": True,
            }
            resp = requests.post(url, json=payload, timeout=10)
            return resp.status_code == 200
        except Exception as e:
            print(f"Telegram error: {e}")
            return False

    def format_signal(self, signal: Dict, risk_info: Dict) -> str:
        """Format signal thành message đẹp cho Telegram"""
        direction = signal["direction"].upper()
        strength = signal["strength"]
        symbol = signal["symbol"]
        trade_type = signal["trade_type"].replace("_", " ").title()
        score = signal["score"]

        # Emoji theo direction
        dir_emoji = "🟢" if direction == "LONG" else "🔴"
        dir_icon = "📈" if direction == "LONG" else "📉"

        # Strength emoji
        strength_map = {
            "STRONG": "🔥 STRONG",
            "MEDIUM": "⚡ MEDIUM",
            "WEAK": "⚠️ WEAK",
        }
        strength_text = strength_map.get(strength, strength)

        # TPs
        tp_lines = []
        for tp in risk_info["tps"]:
            tp_lines.append(f"🎯 TP{tp['level']}: ${tp['price']:,.2f} (R:R 1:{tp['rr_ratio']:.0f}) [{tp['close_pct']}%]")

        # HTF/MTF/LTF details
        htf_details = "\n".join([f"  {d}" for d in signal["htf"]["details"][:3]])
        mtf_details = "\n".join([f"  {d}" for d in signal["mtf"]["details"][:3]])
        ltf_details = "\n".join([f"  {d}" for d in signal["ltf"]["details"][:3]])

        message = f"""
{dir_emoji} *{strength_text} {direction} SIGNAL*
━━━━━━━━━━━━━━━━━━━━
{dir_icon} *{symbol}* | {signal['trade_type'].split('_')[0].upper()} | {trade_type}
💰 *Entry:* ${risk_info['entry']:,.2f}
🛑 *SL:* ${risk_info['sl']:,.2f} ({risk_info['sl_pct']:.1f}%)
━━━━━━━━━━━━━━━━━━━━
{chr(10).join(tp_lines)}
━━━━━━━━━━━━━━━━━━━━
📊 *Score:* {score}/100
⚡ *Leverage:* {risk_info['leverage']}x (Auto)
💎 *Risk:* {risk_info['risk_pct']}% | *Reward:* {risk_info['tps'][-1]['close_pct']}%
📉 *Liquidation:* ${risk_info['liquidation_price']:,.2f}
━━━━━━━━━━━━━━━━━━━━
📈 *HTF ({signal['trade_type'].split('_')[0]}):* {signal['htf']['score']}/100 {signal['htf']['direction'].upper()}
{htf_details}

📊 *MTF:* {signal['mtf']['score']}/100 {signal['mtf']['direction'].upper()}
{mtf_details}

📉 *LTF:* {signal['ltf']['score']}/100 {signal['ltf']['direction'].upper()}
{ltf_details}
━━━━━━━━━━━━━━━━━━━━
⏰ _Signal generated by Crypto Finder Bot_
"""
        return message.strip()

    def send_signal(self, signal: Dict, risk_info: Dict) -> bool:
        """Gửi signal qua Telegram"""
        message = self.format_signal(signal, risk_info)
        return self.send_message(message)

    def send_alert(self, title: str, message: str) -> bool:
        """Gửi alert message"""
        text = f"🔔 *{title}*\n\n{message}"
        return self.send_message(text)


# Singleton
telegram_bot = TelegramBot()
